#librarys

#if you want to work on many types of files, tasks can be achieved by using libraries. makes life easier.
#library is a set of codes, classes, functions,packages.


A collection of modules that are linked together is also known as python library. It has code bundles that can be used again and again in different programs. For programmers it makes python programming easier and simpler. Since then we will not need to compose the same code for various projects.

In [2]:
#these are the most important librarys in Data Science
#numpy is the math library, 2 dimensional - 3d
#panadas is for data sets
#mathplotlib


In [12]:
#numpy

import numpy as np #this is the alisas name of numpy, you can name it what you like, you are taking numpy and its represented as np


In [13]:
#this is showing the lattest version of it
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [14]:
#creat vector of zeros

v=np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
#check what is the memory size used for that operation
print("%d bytes" % (v.size*v.itemsize))

80 bytes


In [17]:
#create a vectorof size 10

v=np.zeros(10)
v[4]=1 #this is replaxing the value of 0 at the 4index to 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [18]:
v=np.arange(10,20) #this is printing the vector of range of 10 to 20 but stops at 19
print(v)

[10 11 12 13 14 15 16 17 18 19]


In [21]:
v= np.arange(10,50) #this is printing the vector of range of 10 to 50 but stops at 49, it can also be refered to as a list
print(v)
print(type(v))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


In [25]:
from numpy.lib.shape_base import vsplit
v=np.arange(50) #starts from 0 to  46, array is a list of numbers
print(v)
v=v[::-1] #this is reverse list
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [26]:
v=np.arange(9).reshape(3,3) #3 dimensional data
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
nz=np.nonzero([1,0,2,0,3,0,5,0,6,0,7,8,0]) #looking for non zero values ajnd it returns the index values of those numbers

print(nz)

(array([ 0,  2,  4,  6,  8, 10, 11]),)


In [29]:
v=np.eye(3) #this prints matrix of vlaues, 3 rows, 3 columns
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
v=np.eye(5) #this prints matrix of vlaues, 5 rows, 5 columns
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
# i want to generate random values, generate 10 random values betweeen 0 and 1

v=np.random.random(10) #np is numpy library and you have one module has a function called random,
print(v)

[0.47734269 0.98783947 0.43551605 0.30076894 0.02426617 0.0778729
 0.48770495 0.8743798  0.02935862 0.56582192]


In [37]:
q =np.random.random((10,10))  #this generates 2 dimension values
print(q)

[[0.4394338  0.30180167 0.18499425 0.68813696 0.62249151 0.60439751
  0.78464335 0.19875503 0.12824752 0.47205158]
 [0.72615469 0.46514749 0.39170436 0.80316748 0.91885733 0.0187055
  0.09092097 0.15918023 0.82972989 0.15787197]
 [0.28466147 0.55464474 0.1514918  0.7681304  0.78798694 0.0288654
  0.85254564 0.05561068 0.82449847 0.71347897]
 [0.6296717  0.67383188 0.68869976 0.08923665 0.22996597 0.42025314
  0.7271887  0.85795779 0.67127863 0.415868  ]
 [0.73289327 0.6242338  0.02642264 0.38391137 0.17372565 0.45373834
  0.92743029 0.56396533 0.99088133 0.59331487]
 [0.08243922 0.34866952 0.76258419 0.14508776 0.29026134 0.53054618
  0.76706245 0.13127822 0.75293339 0.06071066]
 [0.84121966 0.92175924 0.53487156 0.46016377 0.34753642 0.15211163
  0.48398426 0.42634813 0.0900025  0.64156513]
 [0.72092996 0.73204968 0.9671129  0.05490432 0.52194962 0.63296358
  0.22148263 0.1348346  0.70631318 0.41994718]
 [0.23393196 0.23489193 0.21060852 0.55197348 0.1104549  0.35293097
  0.70391749 0

In [38]:
q =np.random.random((2,3,4))  #this makes 2 overall rows [],  with 3 inner rows in those overall rows , 4 values in each row
print(q)



[[[0.51054456 0.29641665 0.1191965  0.32146559]
  [0.34114134 0.49621723 0.05040352 0.03619539]
  [0.90183301 0.48348505 0.83994522 0.81771705]]

 [[0.75707314 0.45288836 0.04855869 0.99067067]
  [0.77378544 0.52530557 0.69548149 0.26092809]
  [0.61348294 0.57286577 0.32479473 0.06818602]]]


In [40]:
h =np.random.random((3,5,2))
print(h)
#data is generated between 0 and 1

#h =np.random.random((3 outter rows ,5 inner rows ,2 elements per row ))

#     #two numbers per row
# [[[0.14657495 0.11036407]   #1 row outter row  , #1 internal row of 5
#   [0.50057361 0.51256106]   #2 internal row of 5
#   [0.11339655 0.74090508] #3 internal row of 5
#   [0.62854022 0.2072085 ] #4 internal row of 5
#   [0.16991964 0.74651901]] #5 internal row of 5

#  [[0.43516508 0.39551729] #2row outter
#   [0.26955838 0.37893141]
#   [0.17721686 0.25625667]
#   [0.91064253 0.83705866]
#   [0.59244441 0.95840729]]

#  [[0.70244962 0.9417962 ] #3row outter
#   [0.35542218 0.32026072]
#   [0.6751833  0.96162901]
#   [0.19739006 0.55754499]
#   [0.74527355 0.26655768]]]

[[[0.07184702 0.88221811]
  [0.95768598 0.91944697]
  [0.49136147 0.02395515]
  [0.07468979 0.04716658]
  [0.80751636 0.4544727 ]]

 [[0.75034914 0.17097558]
  [0.4530556  0.00566637]
  [0.68718955 0.63775856]
  [0.26557481 0.22835334]
  [0.75505172 0.96655211]]

 [[0.94841376 0.12579812]
  [0.16392941 0.390746  ]
  [0.69336566 0.87520166]
  [0.40698744 0.65223741]
  [0.24568978 0.78805444]]]


In [44]:
#this is printing out the random values that are max and min , it will generate new values each time
v= np.random.random((10,10))
v_max, v_min= v.max(), v.min()
print(v_max, v_min)

0.9942830700641812 0.0010079153885846903


In [47]:
#this is printing the mean of this data
v=np.random.random(30)
v_mean= v.mean()
print(v_mean)

0.5227359009557064


In [52]:
v = np.ones((10,10))
print(v)
v[1:-1, 1:-1] = 0 #rows from 1  and skipping by -1 and then column starting at 1 but skipping  by -1
print(v)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [64]:
#generate zeros and convert the inner values to one

v=np.zeros((10, 10))
print(v)
print("after converting the inner values to 1:")
print(" ")
v[1:-1, 1:-1] = 1
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
after converting the inner values to 1:
 
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [67]:
v=np.ones((5,5)) #5 rows of 1s by 5 columns of 1s
print(v)


v=np.pad(v,pad_width=1,mode="constant", constant_values=9) #padding the numbers with 9, you cange the value to anythinhg, only floats
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [68]:
np.nan #nan means null, so null is nothing,so blank, but dont be confused its not 0

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1) #this is false since its a bit more than just 0.3

nan
False
False
nan
False


In [69]:
3 * 0.1

0.30000000000000004

In [71]:
#nan different combos

a= np.nan
b= np.nan
print(a,b)



nan nan


In [101]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


# np.arange(4) creates an array [0, 1, 2, 3]. This is like counting from 0 to 3.

# 1 + np.arange(4) adds 1 to each element of the array, resulting in [1, 2, 3, 4].
#np.diag(...) is a function that constructs a diagonal matrix.
# k=-1 is an argument that specifies which diagonal to use. In this case, it's -1, which means the diagonal below the main diagonal.

Z = np.diag(1+np.arange(4),k=-3)
print(Z)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]]
