In [ ]:
# Converting all things to array, arrays are far better to use then everything else,

In [2]:
import numpy as np
lst1=[11,22,33,44,55,66,77,88,99,110]
arr1=np.array(lst1)
print(type(arr1)) #the list has convrerted to an array

<class 'numpy.ndarray'>


In [3]:
tup1=(12,23,34,45,56,67,78,89,90)
ar2=np.array(tup1)
print(type(ar2))

<class 'numpy.ndarray'>


In [5]:
set1={1,2,3,4,5,0,True,False,"Python","programing"}
arr3=np.array(set1)
print(type(arr3))
arr3

<class 'numpy.ndarray'>


array({0, 1, 2, 3, 4, 5, 'programing', 'Python'}, dtype=object)

In [7]:
dict1={"a":[1,2,3,4,5,0],"b":(True,False),"c":"Python","d":"programing"}
arr4=np.array(dict1)
print(type(arr4))
arr4

<class 'numpy.ndarray'>


array({'a': [1, 2, 3, 4, 5, 0], 'b': (True, False), 'c': 'Python', 'd': 'programing'},
      dtype=object)

In [8]:
str1="python Programming"
arr5=np.array(str1)
print(arr5)

python Programming


In [10]:
#the list has convrerted to an array
lst2=[1,22,3,44,85,66,7,818,99,110]
another_arr=np.array(lst2)
print(type(another_arr))
print(lst2)

<class 'numpy.ndarray'>
[1, 22, 3, 44, 85, 66, 7, 818, 99, 110]


In [12]:
tupie=(190,89,56,34,65,75,23,90)
another_arr2=np.array(tupie)
print(type(another_arr2))
print(tupie)

<class 'numpy.ndarray'>
(190, 89, 56, 34, 65, 75, 23, 90)


In [14]:
set1={1,2,3,4,5,0,True,False,"Chocolate","cake"}
another_arr3=np.array(set1)
print(type(another_arr3))
arr3

<class 'numpy.ndarray'>


array({0, 1, 2, 3, 4, 5, 'programing', 'Python'}, dtype=object)

In [16]:
arr1d=np.array([1,2,3,4,5,67,8,9,10])
print(arr1d)
arr1d.ndim
#this makes this one dimensional

[ 1  2  3  4  5 67  8  9 10]


1

In [18]:
arr2d=np.array([[1,2,3,], [8,9,10]])
print(arr2d)
arr2d.ndim
#this is creating a 2d

[[ 1  2  3]
 [ 8  9 10]]


2

In [19]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])
print(arr3d)
arr3d.ndim

#this is creating a 3d array

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [26]:
arr1d=np.array([3,7,8,9,10])
print(arr1d)
arr1d.ndim
print("this is the one dimension")
#this makes this one dimensional

arr2d=np.array([[1,8,"bob",], [15,"cheese",85]])
print(arr2d)
arr2d.ndim
print("this is the two dimension")
#this is creating a 2d


arr3d = np.array([[[1,2,"fish"],[2,3,"scales"]],[[3,4,"tails"],[4,5,"water"]]])
print(arr3d)
arr3d.ndim
print("this is the three dimension")
#this is creating a 3d array



[ 3  7  8  9 10]
this is the one dimension
[['1' '8' 'bob']
 ['15' 'cheese' '85']]
this is the two dimension
[[['1' '2' 'fish']
  ['2' '3' 'scales']]

 [['3' '4' 'tails']
  ['4' '5' 'water']]]
this is the three dimension
