#Data Preprocesing steps

#1.)Import Libraries

In [ ]:
#these are the mandatory libraries in machine learning, these are the default
#it is not necissaru to have libraries to be called in the first position , it can be called at anywhere in your code.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#2.)Import the Dataset

In [ ]:
path="/content/Data.xlsx"

df=pd.read_excel(path)

df




FileNotFoundError: ignored

In [ ]:
#data preprocessing takes nearly 60-80 percent of time. understandint the data is the most important thing
#column index 0-2 is indpendent index 3 (Purchased)is the dependent column

X=df.iloc[:, 0:3].values
y=df.iloc[:, -1].values

In [ ]:
X #shows all independent values

In [ ]:
y #shows dependent value

#3)Manage Missing Data, work on missing values

###Working on Nan values, the scikit-learn does not work with nan values
###How to manage missing values, 2 things will be done:
* selecting dependent and indepent values

In [ ]:
 #sklearn is the library, the package/api is called impute and within impute theres a class called SimpleImputer

from sklearn.impute import SimpleImputer

#syntax
# sklearn.impute.SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, copy=True, add_indicator=False, keep_empty_features=False)


#most important parameter- strategy, so different strategies to replace the nan value

#mean- after doing the mean of the column, you can replace the nan with the mean
#median- after arragning the values in descind or ascending values, get the middle number, you can replace the nan with the median
#most_frequent-  most frequent value,  you can replace the nan with the most frequent value
#constant- The "constant" strategy allows you to specify a constant value using the fill_value parameter. Missing values in the dataset will be replaced with this specified constant valu

#based on your team you will dicuss the strategies on how to fill out the missing data

In [ ]:
df

# Managing Missing values:
#strategy='mean'


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
X #this result shows the missing values replaced with the mean

# Managing Missing values:
#strategy='median'


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

In [ ]:
#column 1, non numeric values, Country to numeric values


# ['France', 44.0, 72000.0],
#        ['Spain', 27.0, 48000.0],
#        ['Germany', 30.0, 54000.0],
#        ['Spain', 38.0, 61000.0],
#        ['Germany', 40.0, 61000.0],
#        ['France', 35.0, 58000.0],
#        ['Spain', 38.0, 52000.0],
#        ['France', 48.0, 79000.0],
#        ['Germany', 50.0, 83000.0],
#        ['France', 37.0, 67000.0]],

#    f s g
#f   1 0 0
#s   0 1 0
#g   0 0 1


# countries will be replaced by dummy varibles in pandas library , or in sklearn will be called one hot encoder
# ( converting non numeric values to numeric )

#so in this example france numreric value will be 1,0,0, spain is 0,1,0, and germany is 0,0,1

#4)Encoding Categorical Data
one hot encoder sklearn

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X #this replaces the countries into numerical data

# so france is now 0.0, 1.0, 0.0, 0.0,

# spain is 1.0, 0.0, 0.0, 1.0

# germany is 1.0, 0.0, 1.0, 0.0

#Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

##splitting the data into train and test sets



In [ ]:
from sklearn.model_selection import train_test_split #training is teaching the algorithm what kind of data will come
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#The training set is used to teach your machine learning algorithm,
#and the testing set is used to evaluate how well it has learned and can make predictions on new, unseen data.
# random_state=0 is used to ensure reproducibility. You are selecting one set of values like 8 rows of training purpose ,
#it will remain condstant and many for testing purpose
#By setting it to a specific value (in this case, 0),
# you'll get the same random split every time you run the code. This can be helpful for debugging and sharing results

#each random state has a fixed state of random values ,
#so if the state is 1 then all the values in the state will be the same but set to that state so it is fixed

In [ ]:
X_train, X_test, y_train, y_test

#Feature Selection

* it converts all unit data into one format

In [ ]:
from sklearn.preprocessing import StandardScaler #trying to apply changes on existing data
sc= StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])
#this is convering the data into machine readable format, this is the final form

#this is canging age and salary

In [ ]:
X_train


In [ ]:
#importing libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer


In [ ]:
#import the dataset

path="/content/Data3.xlsx"

df=pd.read_excel(path)
df

Country   Age   Salary Most_Freq Constant Purchased
0   France  44.0  72000.0      Pune    India        No
1    Spain  27.0  48000.0      Pune    India       Yes
2  Germany  30.0  54000.0    Mumbai    India        No
3    Spain  38.0  61000.0      Pune    India        No
4  Germany  40.0      NaN      Pune    India       Yes
5   France  35.0  58000.0    Nagpur    India       Yes
6    Spain   NaN  52000.0      Pune    India        No
7   France  48.0  79000.0       NaN    India       Yes
8  Germany  50.0  83000.0    Mumbai    India        No
9   France  37.0  67000.0      Pune      NaN       Yes

In [ ]:
#what columns are independent vs dependent

ind= df.iloc[:,:5].values
ind

dep=df.iloc[:, -1]
dep

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
ind

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, nan, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', nan, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [ ]:
dep

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [ ]:
#handling null values

#mean for numerical

from sklearn.impute import SimpleImputer

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(ind[:, 1:3])
ind[:, 1:3] = imputer.transform(ind[:, 1:3])

In [ ]:
ind

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 63777.77777777778, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.77777777777778, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, nan, 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', nan]], dtype=object)

In [ ]:
#most frequent for non numerical
from sklearn.impute import SimpleImputer

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(ind[:, 3:5])
ind[:, 3:5] = imputer.transform(ind[:, 3:5])

In [ ]:
ind

array([['France', 44.0, 72000.0, 'Pune', 'India'],
       ['Spain', 27.0, 48000.0, 'Pune', 'India'],
       ['Germany', 30.0, 54000.0, 'Mumbai', 'India'],
       ['Spain', 38.0, 61000.0, 'Pune', 'India'],
       ['Germany', 40.0, 63777.77777777778, 'Pune', 'India'],
       ['France', 35.0, 58000.0, 'Nagpur', 'India'],
       ['Spain', 38.77777777777778, 52000.0, 'Pune', 'India'],
       ['France', 48.0, 79000.0, 'Pune', 'India'],
       ['Germany', 50.0, 83000.0, 'Mumbai', 'India'],
       ['France', 37.0, 67000.0, 'Pune', 'India']], dtype=object)

In [ ]:
#encoding categorical data , independent
#this is not creating binary numbers this is just regular numbers
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,3,4])], remainder='passthrough')
ind = np.array(ct.fit_transform(ind))
ind

array([[1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0]], dtype=object)

In [ ]:
#encoding dependent

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dep = le.fit_transform(dep)
dep

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#splitting the data into train and test sets

from sklearn.model_selection import train_test_split #training is teaching the algorithm what kind of data will come
ind_train, ind_test, dep_train, dep_test = train_test_split(ind, dep, test_size=0.2, random_state=0)
ind_train, ind_test, dep_train, dep_test

(array([[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 37.0, 67000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 27.0, 48000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.77777777777778, 52000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

In [ ]:
from sklearn.preprocessing import StandardScaler #trying to apply changes on existing data
sc= StandardScaler()
ind_train[:, 7:] = sc.fit_transform(ind_train[:, 7:])
ind_test[:, 7:] = sc.transform(ind_test[:, 7:])

#applying commonon unit for age and salary

In [ ]:
ind_train, ind_test

(array([[0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.2630675731713538,
         0.12381478548381812],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, -0.25350147960148617,
         0.4617563176278852],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -1.9753983221776195,
         -1.5309334063940299],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.05261351463427101,
         -1.111419780284153],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.6405850472322605,
         1.7202971959575157],
        [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, -0.08131179534387283,
         -0.16751412153693002],
        [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.9518263102018072,
         0.9861483502652313],
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, -0.5978808481167128,
         -0.48214934111933766]], dtype=object),
 array([[0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, -1.4588292694047795,
         -0.9016629672292145],
        [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.984964415747487,
         2.1398108220673926]], dtype=object))